In [2]:
import numpy as np
#Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [15]:
eval('A').shape

(2, 3)

In [16]:
# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

variable_list = ['A','B','C','D','u','v']
dimensions = {key: eval(value).shape for key, value in zip (variable_list, variable_list)}
dimensions

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}

In [23]:
# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = u + v            # u+v
u_minus_v = u - v           # u-v
alpha_times_u = alpha * u   # alpha * u, alpha = 6
u_dot_v = np.dot (u, v )    # u . v
norm_u = np.linalg.norm(u)  # ||u|| 

In [24]:
print (u_plus_v,u_minus_v,alpha_times_u, u_dot_v, norm_u)

[ 9  7 -4  9] [ 3 -3 -2  1] [ 36  12 -18  30] 51 8.60232526704


In [31]:
# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None             # A + C
A_minus_Ctranspose = A - np.transpose(C)   # A - C.T
Ctranspose_plus_3D = np.transpose(C)  + (3 * D)  # C.T + 3*D
B_times_A =  np.dot(B,A)     # B*A
B_times_Atranspose = None  # B*A.T

In [32]:
print (A_plus_C, A_minus_Ctranspose, Ctranspose_plus_3D, B_times_A, B_times_Atranspose)

None [[-4 -7 -3]
 [ 3  6  4]] [[14  3  3]
 [ 2  7  9]] [[-1 -5 -1]
 [ 2  7  4]] None


In [47]:
# Q4: (bonus)

B_times_C = None             # B*C
C_times_B = np.dot(C,B)            # C*B
B_exp_4 = np.linalg.matrix_power(B,4)             # B^4
A_times_Atranspose = np.dot(A,np.transpose(A))   # A*A.T
Dtranspose_times_D = np.dot(np.transpose(D), D)   # D.T*D

In [48]:
print (B_times_C)
print (C_times_B)
print (B_exp_4)
print (A_times_Atranspose)
print (Dtranspose_times_D)


None
[[ 5 -6]
 [ 9 -8]
 [ 6 -6]]
[[ 1 -4]
 [ 0  1]]
[[14 28]
 [28 69]]
[[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]
